services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_rest_starter
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
